
import { Brain, Target, BarChart3, BookOpen, Clock, Users } from "lucide-react";

export const features = [
  {
    title: "AI-Powered Roadmaps",
    description: "Get personalized learning paths generated by advanced AI that adapts to your goals, current skills, and available time.",
    icon: Brain,
    image: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&h=600&fit=crop"
  },
  {
    title: "Goal-Oriented Learning",
    description: "Define your objectives and receive structured roadmaps that guide you step-by-step toward your career goals.",
    icon: Target,
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop"
  },
  {
    title: "Progress Tracking",
    description: "Monitor your advancement with detailed analytics, completion rates, and milestone celebrations.",
    icon: BarChart3,
    image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=600&fit=crop"
  },
  {
    title: "Comprehensive Resources",
    description: "Access curated learning materials, tutorials, and hands-on projects for each step of your journey.",
    icon: BookOpen,
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop"
  },
  {
    title: "Flexible Scheduling",
    description: "Learn at your own pace with roadmaps that adapt to your daily time commitments and schedule.",
    icon: Clock,
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=600&fit=crop"
  },
  {
    title: "Community Support",
    description: "Connect with fellow learners, share progress, and get support from our vibrant learning community.",
    icon: Users,
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop"
  }
];
